name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  space_id: # ID of the Contentful space in form of a string
    description: 'ID of the Contentful space in form of a string'
    required: true
  environment_id: # ID of the Contentful environment in form of a string (ex: staging)
    description: 'ID of the Contentful environment in form of a string (ex: staging)'
    required: true
  access_token: # A production Contentful Content Delivery API key
    description: 'A production Contentful Content Delivery API key'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'
