name: 'Contentful Content Model Doc Generator'
description: 'Generate Markdown docs of a Contentful space Content Model.'
inputs:
  space_id: # ID of the Contentful space in form of a string
    description: 'ID of the Contentful space in form of a string'
    required: true
  environment_id: # ID of the Contentful environment in form of a string (ex: staging)
    description: 'ID of the Contentful environment in form of a string (ex: staging)'
    required: true
  access_token: # A production Contentful Content Delivery API key
    description: 'A production Contentful Content Delivery API key'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
